name: Deploy Next.js static site to GitHub Pages

on:
  push:
    branches: ["main"]   # change if your code branch is not "main"

permissions:
  contents: write   # this allows the action to push to gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js static site
        run: npm run build

      - name: Add CNAME
        run: echo "shraddhayamyar.com" > ./out/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out